<?php
namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAdverts($page, $nbPerPage){
		$qb = $this->createQueryBuilder('a')
				->leftjoin('a.categories', 'cat')
				->addSelect('cat')
				->leftjoin('a.image', 'i')
				->addSelect('i')
//				->orderBy('a.date', 'DESC') bug commun on commente pour le moment
				->getQuery()
				;
				
		$qb->setFirstResult(($page-1) * $nbPerPage)
			->setMaxResults($nbPerPage);
		
		return new Paginator($qb, true);
	}

	public function myFindAll()
	{
		// Méthode 1 : en passant par l'EntityManager
		$queryBuilder = $this->_em->createQueryBuilder()
		  ->select('a')
		  ->from($this->_entityName, 'a')
		;
		// Dans un repository, $this->_entityName est le namespace de l'entité gérée
		// Ici, il vaut donc OC\PlatformBundle\Entity\Advert

		// Méthode 2 : en passant par le raccourci (je recommande)
		$queryBuilder = $this->createQueryBuilder('a');

		// On n'ajoute pas de critère ou tri particulier, la construction
		// de notre requête est finie

		// On récupère la Query à partir du QueryBuilder
		$query = $queryBuilder->getQuery();

		// On récupère les résultats à partir de la Query
		$results = $query->getResult();

		// On retourne ces résultats
		return $results;
	}
	
	
	public function myFind()
	{
		$qb = $this->createQueryBuilder('a');

		// On peut ajouter ce qu'on veut avant
		$qb
			->where('a.author = :author')
			->setParameter('author', 'Marine')
		;

		// On applique notre condition sur le QueryBuilder
		$this->whereCurrentYear($qb);

		// On peut ajouter ce qu'on veut après
		$qb->orderBy('a.date', 'DESC');

		return $qb
			->getQuery()
			->getResult()
		;
	}

	
	public function getAdvertWithCategories(array $categoryNames){
		$qb = $this->createQueryBuilder('a')
				->innerjoin('a.categories', 'c')
				->addSelect('c')
				->where($qb->expr()->in('c.name', $categoryNames));

		return $qb
			->getQuery()
			->getResult()
		;
	}
		
	public function whereCurrentYear(QueryBuilder $qb)
	{
		$qb
			->andWhere('a.date BETWEEN :start AND :end')
			->setParameter('start', new \Datetime(date('Y').'-01-01'))  // Date entre le 1er janvier de cette année
			->setParameter('end',   new \Datetime(date('Y').'-12-31'))  // Et le 31 décembre de cette année
		;
	}	


	public function myFindOne($id)
	{
		$qb = $this->createQueryBuilder('a');

		$qb
			->where('a.id = :id')
			->setParameter('id', $id)
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
	
	
	public function findByAuthorAndDate($author, $year)
	{

		$qb = $this->createQueryBuilder('a');
		$qb->where('a.author = :author')
		   	->setParameter('author', $author)
		 	->andWhere('a.date < :year')
		   	->setParameter('year', $year)
		;
		$this->whereCurrentYear($qb);
		$qb->orderBy('a.date', 'DESC');
		
		return $qb
			->getQuery()
			->getResult()
		;
	}
	
	public function getAdvertsFromDays($days){
		
		$maDate = new \Datetime($days.' days ago');
		$qb = $this->createQueryBuilder('a')
			->where('a.updatedAt <= :maDate')
			->orWhere('a.updatedAt IS NULL AND a.date <= :maDate')
			//->andWhere('a.nbApplications = 0')
			//->andWhere('a.applications IS EMPTY')
			->setParameter('maDate', $maDate)
			->getQuery()
			->getResult();
		
		return $qb;
	
	}
	
	public function isFlood($ip, $seconds){

		$now = new \DateTime();
		$echeance = $now->sub( new \DateInterval('PT'.$seconds.'S'));
		$qb = $this->createQueryBuilder('a')
				->select('a.title, a.date')
				->where('a.date >:date_now')
				->andWhere('a.ip =:actual_ip')
				->setParameters(array('date_now' => $echeance, 'actual_ip' => $ip ))
				->orderBy('a.date', 'DESC')
				->setMaxResults('1');
				
		return $qb->getQuery()
					->getResult();
	}
}
