<?php
namespace OC\PlatformBundle\Repository;

use OC\PlatformBundle\Entity\Advert;
/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends \Doctrine\ORM\EntityRepository
{

/*
uh, he doesn't want it
	public function getFromAdvert(Advert $advert){
		$qb->createQueryBuilder('as')
			->where('as.advert = :advert')
			->setParameter('advert' => $advert);
		return $qb->getQuery()
					->getResult();
	}
*/
}
